### ISSUE TITLE
s

### ISSUE THREAD

**Issue by hpoit** [staticfloat/SHA.jl#15]

**Comment by staticfloat** [comment]
@hpoit Is there something I can help you with?  Looking at the history of issue names, it looks liek you're having trouble with dataframes?

**Comment by hpoit** [comment]
Hi Elliot. DF was fine. It all worked out, my question was wrong. Thanks!

**Comment by staticfloat** [comment]
No problem!  I'm going to close this issue now, please open a new one if you face difficulties in the future.
