### ISSUE TITLE
failure on appveyor

### ISSUE THREAD

**Issue by mlubin** [staticfloat/SHA.jl#23]
Just saw this [weird failure](https://ci.appveyor.com/project/mlubin/ecos-jl/build/1.0.113/job/jojna3vmohs021cy#L62) on Julia 0.5 win64 for https://github.com/JuliaOpt/ECOS.jl/pull/46:

```
LoadError: MethodError: no method matching blocklen(::Type{SHA.SHA2_256_CTX})
Closest candidates are:
  blocklen(!Matched::Type{SHA.SHA1_CTX}) at C:\Users\appveyor\.julia\v0.5\SHA\src\types.jl:92
  blocklen(!Matched::Type{SHA.SHA2_224_CTX}) at C:\Users\appveyor\.julia\v0.5\SHA\src\types.jl:93
  blocklen(!Matched::Type{SHA.SHA2_512_CTX}) at C:\Users\appveyor\.julia\v0.5\SHA\src\types.jl:94
  ...
while loading C:\Users\appveyor\.julia\v0.5\ECOS\deps\build.jl, in expression starting on line 48
```

**Comment by tkelman** [comment]
The type system's kinda broken. Effects a lot of packages and not just on Windows. https://github.com/JuliaLang/julia/pull/17774#issuecomment-237552549

**Comment by mlubin** [comment]
Fair enough, will close this
