### ISSUE TITLE
[Suggestion] JuliaCrypto

### ISSUE THREAD

**Issue by vinctux** [staticfloat/SHA.jl#25]
@staticfloat Some time ago I created the org [`JuliaCrypto`](https://github.com/JuliaCrypto), with the purpose to serve `Krypto.jl` and the further intent to hold all major cryptographic packages in Julia - as JuliaMath, BioJulia, etc do for their field of science. This here is a suggestion to transfer `SHA.jl` into the organisation. As the current owner and lead developer, you would, of course, retain the position :) The merge/transfer would further simplify the creation of a bigger `Hash.jl`, containing the current `SHA.jl`, if that would happen somewhere in the future.

Of course, such a transfer could cause some problems, as all dependent repos would have to update the position of the package (I look at you `METADATA.jl`).

If you agree with this proposal, I would be very glad to see you reply to this thread, as well if you disagree. :-)

**Comment by staticfloat** [comment]
Heh, I like the idea of a JuliaCrypto!  I especially like the icon you made up for it.  :)

For now, I think I would like to keep `SHA.jl` separate and let the JuliaCrypt organization grow itself first.  Once we have a good stable set of contributors to/admins in the organization, we can talk about moving `SHA.jl` over to there as well and creating a `Hashes.jl`.  I would love to see a set of performant, native-julia implementations of hashing functions.
