### ISSUE TITLE
Tag ~~v0.2.2~~ v0.3.0

### ISSUE THREAD

**Issue by kmsquire** [staticfloat/SHA.jl#28]
Ping @staticfloat 

Tag v0.2.2 already exists here, but does not appear in `METADATA.jl`.

The lack of update for SHA.jl is, somehow, keeping `DataStructures.jl` from testing on master: https://travis-ci.org/JuliaLang/DataStructures.jl/jobs/175961386

(Cheers, Elliot!)

**Comment by kmsquire** [comment]
(I just realized that this would drop support for julia v0.3, so the tag needs a bump to v0.3.0)

**Comment by staticfloat** [comment]
@kmsquire I'm in the middle of opening a PR to Metadata.  :)  I tagged v0.2.2 today, but you're right, it really should be v0.3.0!

**Comment by kmsquire** [comment]
:-) Cheers!
