### ISSUE TITLE
SHA1?

### ISSUE THREAD

**Issue by tkelman** [staticfloat/SHA.jl#5]
How different would that be, would it reuse much/any code with what's already here? We can get it from libgit2 (or easier from nettle.jl) so no rush, but would be convenient to have it available in pure Julia at some point.

**Comment by staticfloat** [comment]
Looking at [source code](http://oauth.googlecode.com/svn/code/c/liboauth/src/sha1.c) for `sha1`, it doesn't look too complicated to do from scratch.  I'll add it to the rainy day list, unless someone else gets to it first.  :P

**Comment by tkelman** [comment]
That adds a third permissively-licensed C source then! I already found minix and libsha1 versions. Would be a fun little port if anyone needs it.

Also not sure if libgit2 actually has an easily exposed `sha1sum`-equivalent function to do this.
