### ISSUE TITLE
MD5

### ISSUE THREAD

**Issue by jw3126** [staticfloat/SHA.jl#50]
I have a md5 implementation [here](https://github.com/jw3126/MD5.jl). It uses the same structure as SHA.jl and I copy pasted some SHA.jl code there. This is not ideal, I can think of a couple of other options:

* Merge MD5.jl into SHA.jl
* Create some `HashFunctionsBase.jl` package with common code
* Let MD5.jl depend on SHA.jl

What do you think @staticfloat ?

**Comment by oxinabox** [comment]
Hah, we actually did this at the same time (like to the hour I think).
See: https://github.com/oxinabox/MD5.jl
https://github.com/staticfloat/SHA.jl/issues/46

I did the "Let MD5.jl depend on SHA.jl"

**Comment by jw3126** [comment]
Did you look at the performance? I got rid of all branches in `tranform!`, but `libnettle` is still twice as fast.

**Comment by oxinabox** [comment]
I did not.
Yours looks more performant than mine.
I wanted to get it done with minimum code.

I think the most performant (and also cleanest) would be somewhere between the two.
It'll take some tweaking to find.

**Comment by jw3126** [comment]
We can discuss it here https://github.com/oxinabox/MD5.jl/pull/2

**Comment by staticfloat** [comment]
Just FYI, there is a new JuliaCrypto organization that we're starting to collect packages underneath.

**Comment by jw3126** [comment]
@oxinabox shall we move MD5 to JuliaCrypto?

**Comment by oxinabox** [comment]
We should, but I can't seem to find my invite. @ViralBShah are you sure you sent the invite to the org right?

**Comment by ViralBShah** [comment]
Yeah shows me as pending. Maybe check your spam? Is there a way to see on GitHub itself?

**Comment by oxinabox** [comment]
Ah, if i go to the org page myself I can see it.
Sorted

**Comment by oxinabox** [comment]
Done
https://github.com/JuliaCrypto/MD5.jl
