### ISSUE TITLE
ripemd

### ISSUE THREAD

**Issue by gdkrmr** [staticfloat/SHA.jl#54]
FYI: I made a pure Julia Ripemd implementation, in case you are interested. I stuck to the `update!`, `digest!` interface to keep things consistent. I is currently only Ripemd160, but should be easily extensible.

For short objects it is faster than Nettle and for long objects it takes < 1.5x the time of Nettle.

https://github.com/gdkrmr/Ripemd.jl

**Comment by staticfloat** [comment]
This is great!  We should definitely create a `CryptographicHashes.jl` or something that ties all the julia-native algorithms together.

**Comment by staticfloat** [comment]
Just FYI, there is a new JuliaCrypto organization that we're starting to collect cryptography-related packages underneath.

**Comment by gdkrmr** [comment]
I'll be happy to add the package to the JuliaCrypto organization. I have never done this before, how does it work?

**Comment by staticfloat** [comment]
You go into your project settings and click "transfer", to send it to the `JuliaCrypto` organization.

**Comment by gdkrmr** [comment]
Transferring it to JuliaCrypto gives an error:

You don’t have the permission to create public repositories on JuliaCrypto

**Comment by staticfloat** [comment]
I have invited you to the organization

**Comment by gdkrmr** [comment]
I haven't received any invite.
